- id: latex-operator-differential
  name: latex-operator-differential
  description: 'Checks that `\dd` is used for differential.'
  language: pygrep
  types: [tex]
  entry: '(\\[A-Za-z]*int\b|âˆ«|âˆ¬|âˆ­|â¨Œ|âˆ®|âˆ¯|âˆ°)(?![^\$]*?\\dd\b)'
- id: latex-operator-expectation-value
  name: latex-operator-expectation-value
  description: 'Checks that `\E` is used for expectation value.'
  language: pygrep
  types: [tex]
  entry: '\\math(bb|bf)\{E\}|\b(\ğ„|\ğ”¼|(?<!\\)E\s*(?=[\[\(\{\\]))'
- id: latex-operator-variance
  name: latex-operator-variance
  description: 'Checks that `\Var` is used for variance.'
  language: pygrep
  types: [tex]
  entry: '\\math(bb|bf)\{V\}|\b(\ğ•|\ğ•|(?<!\\)V\s*(?=[\[\(\{\\]))'
